### ISSUE TITLE
Glitch during window stretching, ebiten 2.1.0-rc1

### ISSUE THREAD

**Issue by sedyh** [hajimehoshi/ebiten#1618]
Another issue for window glitches during resize. Glitching is still there.

Before (2.0.8):
![image](https://user-images.githubusercontent.com/19890545/115756532-e661cd80-a3a6-11eb-8173-d79e5ca93437.png)

After (2.1.0-rc1):
![image](https://user-images.githubusercontent.com/19890545/115756789-f5488000-a3a6-11eb-88dc-71fa5b8ada61.png)

Enviroment:
![image](https://user-images.githubusercontent.com/19890545/115757046-042f3280-a3a7-11eb-9197-07ef9dde7e6f.png)

**Comment by hajimehoshi** [comment]
Thanks, but I could not reproduce this error. Would it be possible to test your repository?

**Comment by hajimehoshi** [comment]
OK I think I could reproduce this error:

1. `go run -tags=example examples/windowsize -autoadjusting`
2. Press arrow keys

**Comment by sedyh** [comment]
Yeah, its appearing here too.

![image](https://user-images.githubusercontent.com/19890545/115761565-232fc380-a3ab-11eb-8d29-6184d0de14c7.png)

**Comment by hajimehoshi** [comment]
I think I understand the issue (`(*glfw.Window).GetSize()` is not reliable just after `(*glfw.Window).SetSize()`), and now am thinking how to fix.

**Comment by hajimehoshi** [comment]
Related: #1580

**Comment by hajimehoshi** [comment]
What about  b726d19b004aa5e0e7f5408c0a17954560478759? Thanks

**Comment by hajimehoshi** [comment]
> What about b726d19? Thanks

ping

**Comment by sedyh** [comment]
Glitches not so strong now, but still occurs.
And also now it has become possible to make application to stop rendering (and any other reaction) completely.

Video:
https://drive.google.com/file/d/1EGTyqNf9pgKAPdYkRErCz3w9OtOsu0I2/view?usp=sharing

**Comment by hajimehoshi** [comment]
Does this happen on above `examples/windowsize`?

**Comment by hajimehoshi** [comment]
OK I think I could reproduce this. This seems a pretty rare issue.... Good finding 👍

**Comment by hajimehoshi** [comment]
1. Run `examples/windowsize`
2. Press R to make the window resizable
3. Move the window to the lower-right corner without changing the window size
4. Change the window size by dragging the window's upper-left corner to the desktop's upper-left corner

**Comment by hajimehoshi** [comment]
Apparently `glfw.PollEvents` might never return in some rare situations. https://github.com/hajimehoshi/ebiten/blob/ac9a18931c18407bc1ccae51f61a17f698e95c3e/internal/uidriver/glfw/ui.go#L1220

**Comment by hajimehoshi** [comment]
I believe this was fixed.

@sedyh  Could you take a look at 099d9482f29ef78006025ee63ea2e5590d572221? Thanks!

**Comment by sedyh** [comment]
Hello, reaction stop bug has gone in `099d948`, but glitches are still occur.

**Comment by hajimehoshi** [comment]
Sure, I think I'll be working on it as a different issue. Now glitches happens when resizing the window as the above video shows, right?
