### ISSUE TITLE
Bug: text flickering when resizing screen.

### ISSUE THREAD

**Issue by sedyh** [hajimehoshi/ebiten#2144]
### Problem
Strange text flickering with minimal settings.

![glitch](https://user-images.githubusercontent.com/19890545/173884656-e1f71f4b-a544-4688-b342-8aad6cebeee8.gif)

Happens with this:

```
text.Draw()
ebitenutil.DebugPrintAt()
text.DrawWithOptions()
```
And this:

```go
ebiten.SetWindowResizingMode(ebiten.WindowResizingModeEnabled)
ebiten.SetFPSMode(/* any value, can be ignored */)
if err := ebiten.RunGame(/* your text rendering functions */); err != nil {
	log.Fatal(err)
}
```

### Specs

```
require github.com/hajimehoshi/ebiten/v2 v2.3.3
```

```
inxi -Fxz

System:
  Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
  Desktop: Cinnamon 5.0.7 Distro: Linux Mint 20.2 Uma 
  base: Ubuntu 20.04 focal 
Machine:
  Type: Desktop Mobo: ASRock model: B450 Pro4 serial: <filter> 
  UEFI [Legacy]: American Megatrends v: P3.60 date: 07/31/2019 
CPU:
  Topology: 6-Core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen 
  L2 cache: 3072 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 86238 
  Speed: 2196 MHz min/max: 2200/3600 MHz Core speeds (MHz): 1: 2196 2: 2196 
  3: 2195 4: 2196 5: 2195 6: 2196 7: 2196 8: 2196 9: 2195 10: 2196 11: 2196 
  12: 2196 
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] 
  driver: amdgpu v: kernel bus ID: 0c:00.0 
  Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa resolution: 2560x1440~60Hz 
  OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.35.0 
  5.4.0-91-generic LLVM 12.0.0) 
  v: 4.6 Mesa 21.0.3 direct render: Yes 
Audio:
  Device-1: AMD Navi 10 HDMI Audio driver: snd_hda_intel v: kernel 
  bus ID: 0c:00.1 
  Device-2: AMD Starship/Matisse HD Audio vendor: ASRock 
  driver: snd_hda_intel v: kernel bus ID: 0e:00.4 
  Device-3: Realtek USB2.0 Microphone type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 3-1:2 
  Sound Server: ALSA v: k5.4.0-91-generic 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASRock driver: r8169 v: kernel port: d000 bus ID: 09:00.0 
  IF: enp9s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
  IF-ID-1: br-ed9eba69972d state: down mac: <filter> 
  IF-ID-2: docker0 state: down mac: <filter> 
Drives:
  Local Storage: total: 2.41 TiB used: 976.98 GiB (39.7%) 
  ID-1: /dev/nvme0n1 vendor: Silicon Power model: SPCC M.2 PCIe SSD 
  size: 953.87 GiB 
  ID-2: /dev/sda vendor: Seagate model: ST9500325AS size: 465.76 GiB 
  temp: 37 C 
  ID-3: /dev/sdb vendor: Seagate model: ST1000DM010-2EP102 size: 931.51 GiB 
  temp: 41 C 
  ID-4: /dev/sdc vendor: Western Digital model: WDS120G2G0B-00EPW0 
  size: 111.80 GiB temp: 46 C 
Partition:
  ID-1: / size: 937.40 GiB used: 369.97 GiB (39.5%) fs: ext4 
  dev: /dev/nvme0n1p5 
Sensors:
  System Temperatures: cpu: 57.1 C mobo: N/A gpu: amdgpu temp: 48 C 
  Fan Speeds (RPM): N/A gpu: amdgpu fan: 1215 
Info:
  Processes: 494 Uptime: 8h 05m Memory: 15.57 GiB used: 13.99 GiB (89.9%) 
  Init: systemd runlevel: 5 Compilers: gcc: 9.3.0 Shell: bash v: 5.0.17 
  inxi: 3.0.38 

```

```bash
echo $XDG_SESSION_TYPE
x11
```

**Comment by sedyh** [comment]
This seems to occur with any rendering using screen.Bounds().
This problem does not occur on MacOS.
A better demonstration of what's going on.

<details><summary>Linux Mint 20.2 Uma</summary><br>
<img src="https://user-images.githubusercontent.com/19890545/194295332-5b2dceab-5c15-4e6a-8171-a29374fb6969.gif"/>
</details>

<details><summary>Windows 10 Pro 10.0.19044 build 19044</summary><br>
<video width="320" height="240"><source src="https://user-images.githubusercontent.com/19890545/194297034-37681b43-843e-4221-b03f-cef856208af7.mp4" type="video/mp4"></video>
</details>

**Comment by hajimehoshi** [comment]
@sedyh Could you try ac08ebe0804ede2cc674dadccfb3dde4e9cfec9d? Thanks,

**Comment by sedyh** [comment]
Hello, yes, sure. I saw the post above. I'm waiting for my friend with windows who had a problem.
On my Linux machine, the situation still persists.
I'll write here as soon as we run the minimal example on his machine.

**Comment by hajimehoshi** [comment]
I think I'll give up updating the screen when resizing the window. This is pretty hard to implement it correctly. Instead, the behavior will be the default like just scaling the rendering result.

**Comment by hajimehoshi** [comment]
Note to myself: try https://developer.apple.com/documentation/appkit/nsview/1483514-layercontentsredrawpolicy?language=objc later

**Comment by sedyh** [comment]
Sorry for the very long delay, it behaves the same at `ac08ebe` and `v2.5.0-alpha.4.0.20221029084932-ac08ebe0804e`.

![win-same-bugs-latest](https://user-images.githubusercontent.com/19890545/211168585-e9d2a562-68c6-412a-895b-3ed589360460.gif)

**Comment by hajimehoshi** [comment]
@sedyh That's odd. Are you using DirectX or OpenGL?

**Comment by hajimehoshi** [comment]
> it behaves the same at ac08ebe and v2.5.0-alpha.4.0.20221029084932-ac08ebe0804e.

Wait, both seem old. Please try alpha.11 or later.

**Comment by sedyh** [comment]
> Are you using DirectX or OpenGL?
Isn't newest versions uses directx by default on windows? Please remind me, how to check current runtime.

> Please try alpha.11 or later.
Can I see commit hash? Because it was pulled from via @latest tag.

**Comment by hajimehoshi** [comment]
> Isn't newest versions uses directx by default on windows? Please remind me, how to check current runtime.

Yes and no: if you don't install DirectX or GPU doesn't support it, OpenGL is used.

> Because the second version was pulled via @latest tag.

@latest doesn't take an alpha version but a stable version. Try

```
go get github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.11
```

**Comment by sedyh** [comment]
> Yes and no: if you don't install DirectX or GPU doesn't support it, OpenGL is used.

Does ebitengine have any variable that says what it is currently using?
Does EBITEN_GRAPHICS_LIBRARY is used only to force runtime? Is it shows the current one?

**Comment by hajimehoshi** [comment]
> Does ebitengine has any variable that says what it is currently using?

You can check the current graphics library with [`ReadDebugInfo`](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2#ReadDebugInfo)

**Comment by sedyh** [comment]
Ok, thanks. I'll try that later.

**Comment by sedyh** [comment]
Oh, I see. It now only changes at the end of the resize.
Looks like it working for Win 10. Testring on Linux Mint 20.2.
`ebiten.ReadDebugInfo(...)` outputs DirectX

**Comment by hajimehoshi** [comment]
OK so the issue was fixed. (Smooth rendering on resizing the window again will be another task).

**Comment by tinne26** [comment]
Actually, the flickering still happens with Windows 11 / DirectX (Ebitengine v2.5.4). It's just that since it's not continuous, only for a frame at the end of the resizing, it's much less noticeable. And then with OpenGL the screen doesn't even stretch, it stays the same and gets black borders.

**Comment by hajimehoshi** [comment]
What about v2.6.0-alpha.3?
