### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#70]

**Comment by Austinbcline** [comment]
Trying to get this running on Windows but came across this error:

panic: close of closed channel

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/ui.func┬╖004(0xc0820100e0, 0x280, 0x1e0)
        C:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_gl
fw.go:114 +0x31
github.com/go-gl/glfw3.goFramebufferSizeCB(0x739f30, 0x1e000000280)
        C:/Users/Augustus/go/src/github.com/go-gl/glfw3/window.go:154 +0x61
github.com/go-gl/glfw3._Cfunc_glfwShowWindow(0x739f30)
        C:/Users/Augustus/go/src/github.com/go-gl/glfw3/:768 +0x4c
github.com/go-gl/glfw3.(*Window).Show(0xc0820100e0)
        C:/Users/Augustus/go/src/github.com/go-gl/glfw3/window.go:383 +0x32
github.com/hajimehoshi/ebiten/internal/ui.Start(0x140, 0xf0, 0x2, 0x57fff0, 0x14
, 0xaaa80, 0x0, 0x0)
        C:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_gl
fw.go:119 +0x261
github.com/hajimehoshi/ebiten.Run(0x5af390, 0x140, 0xf0, 0x2, 0x57fff0, 0x14, 0x
0, 0x0)
        C:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/run.go:41 +0x104
main.main()
        c:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/example/shapes/ma
in.go:45 +0x67

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive, locked to thread]:
github.com/hajimehoshi/ebiten/internal/ui.func┬╖0]3()
        C:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_gl
fw.go:81 +0xb9
created by github.com/hajimehoshi/ebiten/internal/ui.init┬╖1
        C:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_gl
fw.go:84 +0x26e

goroutine 6 [sleep, locked to thread]:
github.com/hajimehoshi/ebiten/internal/audio.func┬╖001()
        C:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/internal/audio/au
dio_openal.go:103 +0x59b
created by github.com/hajimehoshi/ebiten/internal/audio.initialize
        C:/Users/Augustus/go/src/github.com/hajimehoshi/ebiten/internal/audio/au
dio_openal.go:106 +0xbc
exit status 2

It seems like the callback is getting called twice.

**Comment by hajimehoshi** [comment]
Thank you for reporting. I'm afraid I don't have a concrete plan to run Ebiten on Windows and the priority is not high because:

* I don't have any environment of Windows. I need to buy a new machine or to set up a VM.
* I'm not sure how many people want to execute Ebiten on Windows. Now this works on Chrome and Firefox, I guess this is not so many.

Contributions including PRs are always welcome anyway.

**Comment by hajimehoshi** [comment]
> panic: close of closed channel

Just guessing, I fixed this and possibly you can avoid crashing.

**Comment by Austinbcline** [comment]
Thank you, it doesn't crash now!

Still isn't working 100% on Windows, I will continue trying to get it going and post any progress I make.

**Comment by hajimehoshi** [comment]
I appreciate your efforts :+1:

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/112 might be related.

**Comment by hajimehoshi** [comment]
Now examples worked on Windows without panics! There are still some troubles at offscreen rendering.

**Comment by hajimehoshi** [comment]
I checked on Windows on Boot Camp, and 'blocks' example worked perfectly.

**Comment by hajimehoshi** [comment]
Now Ebiten supports Windows!
