### ISSUE TITLE
opengl: creating framebuffer failed: 36061

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#810]
Found reports from our game.

36061 = GL_FRAMEBUFFER_UNSUPPORTED?

**Comment by hajimehoshi** [comment]
Huh, this comes from old devices like iPhone 4 or iPad 2...

**Comment by hajimehoshi** [comment]
The report of our games says that this sometimes happen on
iPad2, iPad2, iPad3, iPad4, iPadMini, iPhone4S, iPhone5

CC @wasedaigo

**Comment by hajimehoshi** [comment]
https://www.khronos.org/opengl/wiki/Framebuffer_Object_Extension_Examples

```
//Does the GPU support current FBO configuration?
//Before checking the configuration, you should call these 2 according to the spec.
//At the very least, you need to call glDrawBuffer(GL_NONE)
glDrawBuffer(GL_NONE);
glReadBuffer(GL_NONE);
```

**Comment by hajimehoshi** [comment]
Fixed!

**Comment by jacobsalmela** [comment]
FYI, running v1.9.0, I get this error still on a 2010 Macbook Air (running Ubuntu 20.04.3).  I am happy to help debug if you would like, but realize I am way off the beaten path here.

**Comment by hajimehoshi** [comment]
You mean v2.9.0?

**Comment by jacobsalmela** [comment]
oops yes.

**Comment by hajimehoshi** [comment]
OpenGL on macOS is supported in a best-effort basis, so that's fine. Thanks,

**Comment by jacobsalmela** [comment]
Acknowledged.  Thank you so much!
